version: '3'
services:
  ergo-testnet-node:
    container_name: node-testnet
    image: bellsoft/liberica-openjdk-alpine
    restart: unless-stopped
    volumes:      
      - ./.ergo:/ergo/.ergo
      - ./ergo.conf:/app/ergo.conf
      - ./ergo-5.0.3.jar:/app/ergo.jar
    ports:
      - 9022:9022
      - 9052:9052
    working_dir: /app
    command: java -jar -Xmx2G ergo.jar --testnet -c ergo.conf
